### ISSUE TITLE
Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by Atvicenti** [browning-lab/flare#19]
I have been attempting to debug this for a while, and I can't seem to figure out where things are going wrong. I had this working great, so I am not sure what changed.

I would appreciate any help or advice! Not sure if there is some magic insight anyone has.

This is the input command that generated the error:

java -Xmx600g -jar flare.jar array=false probs=true ref=ref.chr6.vcf.gz ref-panel=ref_panel.txt gt=input.vcf map=plink.chr6.GRCh38.map out=chr6_ancestry

This is the error:

java.lang.IndexOutOfBoundsException: 0
	at ints.IntList.get(IntList.java:120)
	at admix.AdmixStates.initializeCopy(AdmixStates.java:266)
	at admix.AdmixStates.copyData(AdmixStates.java:237)
	at admix.AdmixStates.ibsStates(AdmixStates.java:159)
	at admix.AdmixHmm.runFwdBwdRhoP(AdmixHmm.java:151)
	at admix.ParamEstimator.lambda$estimateRhoP$0(ParamEstimator.java:151)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Terminating program.

**Comment by browning-lab** [comment]
This error usually indicates some problem with the input data.  If you haven't found the cause of this error, email the command line and complete screen output as a copied-and-pasted text or as a text file attachment to browning at uw.edu. I will see if I can determine the cause of the exception from the full screen output.  If I can't determine the cause from the screen output, I will need a small data set that replicates the error in order to determine the cause.
